CREATE TABLE `USER`(
  `ID` BIGINT(20) AUTO_INCREMENT,
  `NAME` VARCHAR(255),
  `EMAIL` VARCHAR(255) NOT NULL UNIQUE,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `ACTIVE` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`ID`)
);