CREATE TABLE `USER`(
  `ID` BIGINT(20) AUTO_INCREMENT,
  `NAME` VARCHAR(255),
  `EMAIL` VARCHAR(255) NOT NULL UNIQUE,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `ACTIVE` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`ID`)
);

INSERT INTO USER(NAME, EMAIL, PASSWORD) VALUES('Ivan Masich', 'w3cvalid@gmail.com', '$2a$15$Ee8.XsH1Zq.MOhTFkHvPHuPWrv6j3ajk241CuvuLkotNIzgCLG0lS');