CREATE TABLE `APPLICATION_FILTER` (
  `ID` BIGINT(20) AUTO_INCREMENT,
  `APPLICATION_ID` BIGINT(20) NOT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  `NAME` VARCHAR(256) NOT NULL,
  `DESCRIPTION` VARCHAR(1024) NOT NULL,
  `LEVEL` VARCHAR(32) NOT NULL,
  `LOGGER_NAME` VARCHAR(512) NOT NULL,
  `MESSAGE` TEXT NOT NULL,
  PRIMARY KEY (`ID`)
);
