CREATE TABLE `FAVORITE_LOG_MESSAGE` (
  `ID` BIGINT(20) AUTO_INCREMENT,
  `USER_ID` BIGINT(20) NOT NULL,
  `LOG_MESSAGE_ID` BIGINT(20) NOT NULL,
  `NOTES` TEXT NOT NULL,
  `CREATED` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`)
);
