CREATE TABLE `LOG_MESSAGE_ISSUE` (
  `ID` BIGINT(20) AUTO_INCREMENT,
  `LOG_MESSAGE_ID` BIGINT(20) NOT NULL,
  `FROM_USER_ID` BIGINT(20) NOT NULL,
  `TO_USER_ID` BIGINT(20) NOT NULL,
  `DESCRIPTION` TEXT NOT NULL,
  `STATUS` VARCHAR(32) NOT NULL,
  `CREATED` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`)
);
