CREATE TABLE `COMMENT` (
  `ID` BIGINT(20) AUTO_INCREMENT,
  `LOG_MESSAGE_ID` BIGINT(20) NOT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  `COMMENT` TEXT NOT NULL,
  `CREATED` TIMESTAMP NOT NULL,
  `PATH` VARCHAR(1024),
  PRIMARY KEY (`ID`)
);
